spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swzl?useSSL=false
    username: user
    password: wr000000
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
      host: smtp.163.com
      username: rongwang1998@163.com
      password: wr000000
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
logging:
  level: warn
  file: /log/myLog.log
loginVerify: true
sendEmail: false
sendMessage: false
server:
  port: 8080